# Generated by Django 5.1.3 on 2025-02-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_component_assembly'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='inventory_qty',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
